### ISSUE TITLE
Sorcery + Pretender wont stop impersonating

### ISSUE THREAD

**Issue by mikestephens** [ankane/pretender#10]
Hey! I love the gem, but unfortunately when hit the "stop_impersonating" method in my users controller and refresh the page it goes right back. The problem does go away on a full logout.

Here is my controller method:
```
  def stop_impersonating
    stop_impersonating_user
    redirect_to users_path
  end
```

And here is a gif of the problem:
http://i.imgur.com/aCYeDpC.gifv

Versions: 
rails (= 4.2.4)
pretender (0.2.1)
sorcery (0.9.1)

Let me know if there is any other information I can provide! Thank you for an awesome gem!

**Comment by ankane** [comment]
Hey @mikestephens, it's possible the user isn't being impersonated. I'd log `current_user` and `true_user` on `stop_personating` action to see if that's the case. (the imgur link isn't working, fwiw)

**Comment by mikestephens** [comment]
Hey! sorry about the imgur link. I fixed it in the original post. So I just double checked and `current_user` is set to the impersonated user and `true_user` is set to my true user as expected.

**Comment by ankane** [comment]
Can you log `session` as well?  There should be a key called `impersonated_user_id` that is set to `nil` after `stop_impersonating_user` is called. https://github.com/ankane/pretender/blob/master/lib/pretender.rb#L43

**Comment by mikestephens** [comment]
Sure thing! It looks like the session is removed initially but upon page refresh it is back

```
[7] pry(#<UsersController>)> session[:impersonated_user_id]
=> 9
[8] pry(#<UsersController>)> current_user.id
=> 9
[9] pry(#<UsersController>)> true_user.id
=> 8
[10] pry(#<UsersController>)> exit

From: app/controllers/users_controller.rb @ line 119 UsersController#stop_impersonating:

    116: def stop_impersonating
    117:   binding.pry
    118:   stop_impersonating_user
 => 119:   binding.pry
    120:   redirect_to users_path
    121: end

[1] pry(#<UsersController>)> session[:impersonated_user_id]
=> nil
[2] pry(#<UsersController>)> current_user.id
=> 8
[3] pry(#<UsersController>)> true_user.id
=> 8
[4] pry(#<UsersController>)> exit

AFTER PAGE RELOAD:

From: app/controllers/users_controller.rb @ line 57 UsersController#index:

    55: def index
    56:   @users = User.search(params[:search]).page params[:page]
 => 57:   binding.pry
    58: end

[1] pry(#<UsersController>)> session[:impersonated_user_id]
=> 9
[2] pry(#<UsersController>)> current_user.id
=> 9
[3] pry(#<UsersController>)> true_user.id
=> 
```

**Comment by ankane** [comment]
I'm not sure why the session update wouldn't stick. Do you see this issue with other session variables?

Also, be sure impersonate_user isn't accidentally being called in a before_action.

**Comment by mikestephens** [comment]
Impersonate user does not get called anywhere outside of the user controller action. Other session variables seem to work as intended. 

I will note that I just released my changes to my production server and this issue seems to be only on my local machine. It must be something funny with my local set up.

**Comment by ankane** [comment]
I'm not really sure where to go from here.  Let's close, but please follow up if you figure it out so others can benefit.

**Comment by himanshinigam09** [comment]
Hey! the gem is great. But what I want is that when a true user impersonating as the current user, he should not be able to perform any action (create, update, delete) or make any updates in the user's account.

**Comment by ankane** [comment]
Hey @himanshinigam09, you can check if `current_user == true_user` in the controller action or `before_action`. Also, please create a new issue for new questions so we're not creating noise for others.
