### ISSUE TITLE
Log in as different Model

### ISSUE THREAD

**Issue by kevinjbayer** [ankane/pretender#14]
Is it possible for this gem to be used with different models? For instance, I want an AdminUser model to be able to login as any User. It works great when I set it up User to User, but not when I use the AdminUser to User.

**Comment by ankane** [comment]
Pretender wasn't built for this, but you can try using the `with` option to see if it works. https://github.com/ankane/pretender#configuration

**Comment by kevinjbayer** [comment]
Yeah, I was attempting to update the impersonates method because I can tell it's using the same scope of 'user', including in true_method:

```
def impersonates(scope = :user, opts = {})
    impersonated_method = opts[:method] || :"current_#{scope}"
    impersonate_with = opts[:with] || proc { |id| scope.to_s.classify.constantize.where(:id => id).first }
    true_method = :"true_#{scope}"
    session_key = :"impersonated_#{scope}_id"
    impersonated_var = :"@impersonated_#{scope}"
```

I ended up modifying [switch_user](https://github.com/flyerhzm/switch_user) to fit my needs and it mostly works, but not as cleanly as I like your code. Wish I had time to do figure out a way for this to work right now, but I don't. I'll close. Thanks for responding.

**Comment by stevenharman** [comment]
We have an `Administrator` and then an `Account` model. We were hoping to have `Administrator`s impersonate an `Account`. If this isn't supported, and it seems not to be, maybe add that to the README?

**Comment by ankane** [comment]
Hey @stevenharman, this is supported. See the Configuration section of the readme. You'll want to put `Administrator` in the `with` part.

**Comment by stevenharman** [comment]
Yeah, this ended up breaking b/c Pretender isn't compatible with route-based constraints. e.g., 

```ruby
authenticate :account do
  # define some resources here
end
```

For posterity, and folks landing here in the future, I ended up rolling my own solution: https://github.com/ankane/pretender/issues/22#issuecomment-321456371

**Comment by artur79** [comment]
@ankane what would be the setup if I use Devise and admin is Admin class and user which I want to impersonate is User class ? I'm getting all the time error: Must be logged in to impersonate.
Tried this _impersonates :user, method: :current_user, with: -> (id) { Admin.find_by(id: id) }_ but no success

**Comment by ankane** [comment]
Hey, sorry for the confusion. Just took a look at this again for #55 and it's not supported (not sure why I thought it was in https://github.com/ankane/pretender/issues/14#issuecomment-321442956).
