### ISSUE TITLE
current_user reverts back to true_user after redirect

### ISSUE THREAD

**Issue by newton10471** [ankane/pretender#15]
I love the idea and simplicity of this gem but having difficulty getting it to work with my app.  Immediately after calling the impersonate_user method in my app, current_user and true_user are set to the correct users.  However, once my app hits the controller specified in the redirection after calling impersonate_user, current_user reverts back to being the same as true_user.  session[:impersonated_user_id] is still correct (the impersonated user’s id), but @impersonated_user for some reason reverts back to true_user.  I put in breakpoints and used .source_location in each case to confirm that the current_user that’s being called is pretender’s current_user. Anyone seen this before or know what might be the cause, or a hint on how to debug it?

**Comment by newton10471** [comment]
Think I figured out my issue.  Thanks!

**Comment by ankane** [comment]
Great, if there's anything others can learn from it, feel free to add details.

**Comment by hoenth** [comment]
@newton10471 What was your issue, as I am experience something similar. I use an Admin model and so have `impersonate :admin`. I am also using Devise. 

The impersonate action redirects to the admin index action. In the index action controller method, both current_admin and true_admin are correct, but in the index view, current_admin is set back to true admin. Though @impersonated_admin is correct. 

Perhaps devise, when using a non-standard scope defines the view helper in a different way than the controller helper. 

Interestingly, I also use CanCanCan, and the ability is for the correct impersonated user. 

@ankane Thank you for this beautiful little piece of coding magic. I hope I can get it to work for my situation. 

Any thoughts would be greatly appreciated?

**Comment by newton10471** [comment]
@hoenth my issue had nothing to do with the pretender gem, just my brain not working properly.  I was using the wrong attribute to search by in the lambda component of impersonates :user, with:

**Comment by hoenth** [comment]
Thanks @newton10471. @ankane do you have any insights into where I could start looking as to why the current_admin is not using the @impersonated_admin value?
