### ISSUE TITLE
current_user must be defined before the impersonates method when using the Clearance gem

### ISSUE THREAD

**Issue by conwayanderson** [ankane/pretender#17]
I'm getting the error `current_user must be defined before the impersonates method` when trying to implement this in an app that uses the Clearance user auth gem, which does have a current_user method. I'm not sure how to adjust the implementation to work, though.

![screenshot 2017-06-06 19 18 57](https://user-images.githubusercontent.com/1882439/26859556-71fea460-4aed-11e7-8143-9112678442de.png)

**Comment by ankane** [comment]
Hey @conwayanderson, thanks for reporting 👍  This is fixed on master.

**Comment by rbazinet** [comment]
@ankane I'm getting this error in and RSpec test. Any suggestions on what's needed to test my controller methods that use Pretender?

**Comment by armansa** [comment]
I have same problem. To fix it I added `devise_for :users, only: []` in config/routes.rb
But then tests fail.
