### ISSUE TITLE
Following the documentation but cannot get it to work

### ISSUE THREAD

**Issue by hundsim** [ankane/pretender#18]
I've installed Pretender (0.2.1) on Rails 5.1.

If you see the commented out lines in the method below, the passed user id doesn't get assigned to `current_user`.

In users_controller.rb

    def impersonate
	  # current_user.id => 20
	  user = User.find(params[:id])
	  # user.id => 300
	  impersonate_user(user)
 	  # current_user.id => 20
      ...

in application_controller.rb  

    impersonates :user,
       method: :current_user,
       with: -> (id) { User.find_by(id: id) }
    before_action :current_user

	def current_user
	  if session[:user_id]
	    @current_user ||= User.find(session[:user_id])
	  end
	end

**Comment by ankane** [comment]
Hey @hundsim, try putting `impersonates` after the `current_user` method is defined.

**Comment by ankane** [comment]
Cleaning up issues
