### ISSUE TITLE
Working in development, Not working in production

### ISSUE THREAD

**Issue by seyonv** [ankane/pretender#21]
Deployment is on Heroku.  Nothing I can notice in production.rb would cause this issue and
there's no production specific gem that would cause this either.

Any ideas or is this a problem anyone else has experienced before?

**Comment by seyonv** [comment]
Never mind, nothing related to this gem

**Comment by thapakazi** [comment]
@seyonv what was the issue, I am facing the similar. 
after commenting out the impersonates section, then only app started working on other envs.
```
class ApplicationController < ActionController::API
  before_action :authenticate_user!
  include DeviseTokenAuth::Concerns::SetUserByToken
  # impersonates :user
  ...
end
```
  **Are there any change this gem tied up to environment specific configuration ??**

**Comment by onwardmk** [comment]
> @seyonv what was the issue, I am facing the similar. after commenting out the impersonates section, then only app started working on other envs.
> 
> ```
> class ApplicationController < ActionController::API
>   before_action :authenticate_user!
>   include DeviseTokenAuth::Concerns::SetUserByToken
>   # impersonates :user
>   ...
> end
> ```
> 
> **Are there any change this gem tied up to environment specific configuration ??**

Did you figure this out? I'm trying to do the same thing.
