### ISSUE TITLE
Help keeping current_user correct

### ISSUE THREAD

**Issue by rmccown** [ankane/pretender#31]
I'm having the same issue as this issue from earlier in the year.

https://github.com/ankane/pretender/issues/15

I have a rudimentary user session based on a session cookie.  Essentially, my current_user function looks like this

`
  def current_user
    @current_user ||= User.find_by(id: session[:user_id])
  end
`

In my user controller the redirect sets current_user correctly, but in debugging by the time I get back to the page, current_user is now equal to true_user.  Yet, my CanCan abilities are correct for the impersonated user, so *something* is correct.  

This isnt a bug, but since there isnt a forum for this gem I'd like to open a discussion about this.  I'm sure its something simple I'm just not seeing.

TIA

**Comment by ankane** [comment]
Hey @rmccown, thanks for reporting. A few things:

1. Can you try `master` to see if the issue is still happening? It has additional warnings that could help debugging.
2. Is impersonation not working in the controller, view, or both?

**Comment by rmccown** [comment]
I think I can give it a try over the weekend.  Thanks

**Comment by rmccown** [comment]
Just testing now. Same thing is happening with the latest.

Some debugging.  In the controller, I'm the correct, impersonated user, but in the view, current_user is still equal to true_user.

**Comment by ankane** [comment]
Just to clarify: everything is working correctly in controller, but `current_user` is always equal to `true_user` in views?

**Comment by ankane** [comment]
If that's the case, try adding `helper_method :current_user` after `impersonates :user` in your controller and see if that fixes it.

**Comment by rmccown** [comment]
> Just to clarify: everything is working correctly in controller, but current_user is always equal to true_user in views?

Correct

> If that's the case, try adding helper_method :current_user after impersonates :user in your controller and see if that fixes it.

Yes, that does fix it.  Thanks!
