### ISSUE TITLE
Sample on using this with token authentication on Rails 5 API-Only

### ISSUE THREAD

**Issue by micahlisonbee** [ankane/pretender#33]
Can anyone give an example of how to use this with token auth? Specifically Devise + Simple Token Authentication. Rails 5 API-Only mode

@Littlejd1997 mentions using this with token auth in #19 

Thanks.

**Comment by ankane** [comment]
Hey @micahlisonbee, you'll need to add session storage to your app and pass the session cookie on subsequent requests to the API. http://edgeguides.rubyonrails.org/api_app.html#other-middleware

**Comment by micahlisonbee** [comment]
It actually just works for me with only adding the middleware:

```ruby
config.middleware.use ActionDispatch::Cookies
config.middleware.use ActionDispatch::Session::CookieStore
```

It's working on subsequent requests even though I'm not sending any cookies up which leaves me a bit confused how the session is keeping the state. Any ideas?

**Comment by ankane** [comment]
@micahlisonbee My guess is your HTTP libraries is storing cookies and sending them with subsequent requests.

**Comment by micahlisonbee** [comment]
@ankane I am using the GraphiQL (graphql-ruby) and I'm not sure it's sending/stories any cookies.

**Comment by ankane** [comment]
@micahlisonbee You can check by adding the following code to your controller:

```ruby
p request.cookies.to_hash
p request.session.to_hash
```

**Comment by micahlisonbee** [comment]
@ankane yes it was sending cookies. We changed our web app to `credentials: 'include'` and set our Rails CORS settings to accept credentials and it works now. Feel free to close this. Thanks!

**Comment by f-g-p** [comment]
Hi, 
I'm currently implementing this feature with a React + Rails application. 
My understanding was that with the API, each API call was independent and would go through authentication. So I figured I could store the impersonating state in the front end (redux store or cookie), and manually set up the current_user and true_user in the authentication method, without having to deal with middleware.

Am I missing something? Would you see any flaws with this approach? 

Thanks a lot!
