### ISSUE TITLE
not working in apartment multitenant

### ISSUE THREAD

**Issue by surajit** [ankane/pretender#36]
I'm using ruby-2.4.2 and Rails-5.1.4 and using 'apartment' gem for multitenancy. The impersonate not working to switch multi user account.

**Comment by ankane** [comment]
Hey @surajit, can you provide more detailed instructions on how to reproduce, including what "not working" means?

**Comment by surajit** [comment]
we've different databases and user associated with different databases, so as a superadmin we can switch one databases to another database by user what actually 'pretender' done. This functionality not working in apartment. can you please suggest what we need to do here.

**Comment by ankane** [comment]
My suggestion would be to fork the gem, add some logging, and understand why it's not working with your set up. From there, we can then consider possible changes.

**Comment by ankane** [comment]
Cleaning up stale issues
