### ISSUE TITLE
Working fine in development but not in production with Unicorn

### ISSUE THREAD

**Issue by jonfer** [ankane/pretender#39]
Its working fine in development environment. But in production I get this error:
> INFO -- : Refreshing Gem list
> NoMethodError: undefined method `impersonates' for ApplicationCable::Connection:Class

In development I'm using puma and in production unicorn, is it possible that this doesn't work with unicorn?

**Comment by jonfer** [comment]
I forgot to detail that the problem is only in ActionCable, looks like it doesn't load the Gem or something... 

I tried to test it in development with Unicorn but my application needs Puma-dev with subdomains.

**Comment by ankane** [comment]
Cleaning up issues. If you get to the bottom of it, let me know.

**Comment by verlinden** [comment]
Hi,

@ankane I've got the same issue in staging or production environments. You can reproduce it in local by adding `config.eager_load = true` in development.rb

Seems like the impersonates  method is called before your `ActiveSupport.on_load(:action_cable)` callback ?

**Comment by ankane** [comment]
Thanks @verlinden, can you give master a shot?

**Comment by scharrier** [comment]
@ankane I got the exact same issue in staging and production (for the same `eager_load` config) and using the master version of pretenders fixed it. Thanks!

**Comment by ankane** [comment]
Thank you both, just released a new version.
