### ISSUE TITLE
Why fetching impersonation is only if user is logged?

### ISSUE THREAD

**Issue by m7moud** [ankane/pretender#4]
I'm using different models for users and admins, and of course admins can impersonate users.

**Comment by unregistered** [comment]
+1... I didn't realize this was a dealbreaker before I started using this module.

**Comment by ankane** [comment]
This is done to prevent a situation where a user (who let's say is an admin) logs out but the impersonation sticks, so the next user who logs in on the same machine (who may not be an admin) will be impersonating (security issue).
