### ISSUE TITLE
current_user equals true_user after override

### ISSUE THREAD

**Issue by HenriqueMorato** [ankane/pretender#45]
I'm having a issue related to #31 

When we override current_user:

```
def ApplicationController < ActionController::Base
  impersonates :user

  def current_user
    super.decorate
  end
end
```

The `super` call not return the current impersonated user but the `true_user` there's a way to bypass this?

**Comment by ankane** [comment]
Hey @HenriqueMorato, moving `impersonates` after the new method should fix it. I'm not sure if there's a way to make it work in this situation, as there's already a bit of metaprogramming magic to make it work as is, but feel free to submit a PR if you can figure it out.

**Comment by HenriqueMorato** [comment]
Hey @ankane 

I've tried that before, the problem with this approach is that `current_user` returns a not decorated user so some of my methods will fail :( 

There's some way to expose a variable to not have to@ call `super` on current_user but call the variable?

I'll try to take a look and explore the code in detail this weekend.

**Comment by ankane** [comment]
Cleaning up issues. As you mentioned, I'd try digging into the code to see if you can make it work for you.
