### ISSUE TITLE
current_user helper

### ISSUE THREAD

**Issue by dclausen** [ankane/pretender#49]
When using pretender and devise, I noticed that the controller method for current_user is being updated to the impersonated user. However, when calling current_user within a view via <%= current_user %>, I see the true user instead. As a workaround, I updated the view to use <%= controller.current_user %>. Is this expected?

**Comment by ankane** [comment]
Hey @dclausen, I think it may be something specific to your application, as I'm not able to reproduce with a fresh Rails app.

You can try adding `helper_method :current_user` after `impersonates :user` to fix it.

**Comment by ankane** [comment]
Closing due to no response
