### ISSUE TITLE
Destroying the session?

### ISSUE THREAD

**Issue by jondavidjohn** [ankane/pretender#50]
Is there a reason this gem destroys the user's session when stopping the impersonation?

https://github.com/ankane/pretender/blob/6c6e970ea1ef16ab5c32fba3765af1df38e8a9f4/lib/pretender.rb#L66

Seems like you should be able to stop the impersonation (of another user), and just revert back to the true user?

**Comment by ankane** [comment]
Hey @jondavidjohn, only the `impersonated_#{scope}_id` key is deleted, not the user session.

**Comment by jondavidjohn** [comment]
Interesting, I'm running into a situation where it actually logs me out fully.  I'll do a little debugging to see if I can pinpoint why.

**Comment by akimthedream** [comment]
Hey @jondavidjohn, happy new year! I ran into the same issue. Does your `before_action :require_admin!` perform the logout? For me it had to be `before_action :require_admin!, except: [:stop_impersonating]`. The documentation is a little bit misleading here.

**Comment by ankane** [comment]
Thanks for sharing @akimthedream. Closing this out since it doesn't appear to be an issue with Pretender.
