### ISSUE TITLE
true user reset after UI refresh

### ISSUE THREAD

**Issue by yuvalbau** [ankane/pretender#54]
I implemented the pretender gem on my app in order to use impersonations .
Im using Devise auth and the issue is :
after impersonating  the current_user and true_user are set correctly, but once i refresh the application , true_user is reset to be similar as the current_user (the impersonated one ).

thanks :)

**Comment by ankane** [comment]
Hey @yuvalbau, I'm not exactly sure how to reproduce, but my guess is the session is not persisting between requests or is being reset.
