### ISSUE TITLE
User and admin role model

### ISSUE THREAD

**Issue by Haider-Ali-RoR** [ankane/pretender#55]
Hi @ankane, i have two separate models `Admin` and `User` and i want to impersonate the `User` by an `Admin`. I also followed the `with` part in configuration but nothing happened. Please guide me what actually i should do to achieve this task. Thanks!

**Comment by ankane** [comment]
Hey @Haider-Ali-RoR, it looks like this isn't supported (not sure why I thought it was in https://github.com/ankane/pretender/issues/14#issuecomment-321442956), so you'll probably want to try a different gem.
