### ISSUE TITLE
Auto logout user

### ISSUE THREAD

**Issue by sulemanuzair** [ankane/pretender#57]
Hi there,
I wanted to ask whether the functionality to auto log-out pretended user should be added in gem. Currently, I am thinking to achieve it through devise timeoutable module for my case.

Thanks :)

**Comment by ankane** [comment]
Hey @sulemanuzair, it's an interesting idea, but think it's probably not common enough of a need to add. If you find a way to make it work, would be great to share for others who are interested.

**Comment by sulemanuzair** [comment]
Sure. I moved to some other tasks during this time. But will definitely share my results in this week.

**Comment by ankane** [comment]
Cleaning up issues, but still feel free to share

**Comment by sulemanuzair** [comment]
@chadwilken Sorry, I couldn't continue on this but i had the idea to follow Devise's timeoutable module for this case.
