### ISSUE TITLE
Cancancan ability uses true_user instead of impersonated user

### ISSUE THREAD

**Issue by goulvench** [ankane/pretender#61]
Hi, thanks for this gem and the useful readme, it was very easy to setup.

However I want to view the interface as seen by the impersonated user, which doesn't work because CanCanCan keeps using `true_user` to filter data and allowed actions (I'm relying on [`load_and_authorize_resource`](https://github.com/CanCanCommunity/cancancan/blob/develop/docs/controller_helpers.md#authorize_resource-load_resource-load_and_authorize_resource)). 
Any idea what I'm doing wrong?

I'm using [`CurrentAttributes`](https://api.rubyonrails.org/classes/ActiveSupport/CurrentAttributes.html) too, but even if I set  `Current.user` right after impersonating, it doesn't work either.

**Comment by ankane** [comment]
Hi @goulvench, I'd first check that `current_ability` hasn't [been customized](https://github.com/CanCanCommunity/cancancan/blob/cbc81ed56d9467ffe07370576a218981aaf9468f/docs/changing_defaults.md) to use `true_user`. If that's not the case, I'd recommend forking CanCanCan and adding debugging to see what's going on.

**Comment by goulvench** [comment]
Indeed, access rights were being cached deep down in the code (to avoid hitting the API) when in dev. Works like a charm now, sorry for the noise and thanks for this gem!

**Comment by francescor** [comment]
I had the same weird effect, and the reason was that I was using `@current_user` instead of (the recommended) `current_user` method.     Indeed, in my setup, `@current_user`  return the `true_user`.
