### ISSUE TITLE
Support multiple scopes 

### ISSUE THREAD

**Issue by alexdunae** [ankane/pretender#64]
Thanks for maintaining a great gem.  

I've come across the same limitation as a few other people: I have an `Administrator` scope and a `Customer` scope.  I want `administrators` be able to impersonate `customers`, without being logged in as a `customer`.

This has been requested before...
- https://github.com/ankane/pretender/issues/14
- https://github.com/ankane/pretender/issues/40
- https://github.com/ankane/pretender/issues/55

This line is the culprit...
https://github.com/ankane/pretender/blob/805880f1eaae90d3aee681715630d00526546fb4/lib/pretender.rb#L60

It appears the purpose of this is to clear out impersonations from logged-out super users.

https://github.com/ankane/pretender/blob/805880f1eaae90d3aee681715630d00526546fb4/lib/pretender.rb#L40-L48

This is a nice sanity check, but it would be great if we could pass in our own method to check the login status of the super user.

Would you be open to a PR that adds a new option to the `impersonates` call so we could provide our own logged in check?

Something like...

```ruby
impersonates :customer, ensuring: :administrator_signed_in?
```

This would solve my issue (and the others listed) with minimal change to the surface area and no change to the behaviour.

If this appeals... I'm happy to put something together.

And, if so... do you have a preference for the option name?

- `ensuring: :administrator_signed_in?`
- `log_in_guard: :administrator_signed_in?`
- `sudo: :administrator_signed_in?`
- `when: :administrator_signed_in?`
- `if: :administrator_signed_in?`

**Comment by ankane** [comment]
Hi @alexdunae, it isn't something I'd like to support, but someone is welcome to create a fork that supports it.

**Comment by vegasdevguy** [comment]
@alexdunae what did you end up doing?
