### ISSUE TITLE
"Current.user" causing issues with "true_user"?

### ISSUE THREAD

**Issue by Shpigford** [ankane/pretender#67]
I'm setting up pretender like so...

```
class ApplicationController < ActionController::Base
  impersonates :user, method: Current.user
end
```

However, when I do `Current.user != true_user` I get the following error:

`current_user must be defined before the impersonates method`

I almost certainly am doing something wrong, but just not sure what. Any suggestions on debugging this?

**Comment by ankane** [comment]
Hi @Shpigford, the method you want to impersonate must be defined in the controller. You could do:

```ruby
class ApplicationController < ActionController::Base
  def current_user
    Current.user
  end

  impersonates :user
end
```

but the impersonation will only happen for calls to `current_user`, not `Current.user`.

**Comment by morgler** [comment]
That is sad. Is there a way to get impersonation with Current.user? I'm reluctant to introduce a current_user when all the code is built on Current.user (the standard in latest Rails).
