### ISSUE TITLE
Current User becomes true user on invitable email

### ISSUE THREAD

**Issue by ChakreshwarSharma-BTC** [ankane/pretender#8]
Hi,
I am using devise_invitable for sending invitation email.
When I impersonate a user & invite some user , then the invitation is send by true user & not the impersonated_user(current_user)

**Comment by ankane** [comment]
Hey @ChakreshwarSharma-BTC, I haven't used `devise_invitable`, so will need you or someone else to debug. Closing for now, but feel free to reopen if you find anything.
